### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by 11nekomamire** [11nekomamire/furima-29702#9]
#URL
https://furima-29702.herokuapp.com/

- Basic認証のID =>  yusaku
- パスワード      =>  miya0000

| mail                                      | password  | Options   |
| -------------------------- | ---------- | --------- |
| sample10@sample.com     | sample10  | seller       |
| sample20@sample.com    | sample20  | buyer       |

- カード番号                =>  4242424242424242
- 期限                           =>  4 / 40  (月/年)
- セキュリティコード    =>  123

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
### [修正箇所]
**・画像が0枚のときは出品できないようにしましょう！**

**・ログインしていないユーザーは購入ページに遷移しようとすると、ログインページではなくトップページに遷移するので、ログインページに遷移するようにしましょう！**

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
